time: 0 #do not touch
config:
  backup_name: "end_backup"
  world_name: "world_the_end"
  time_between_actions: 40 #ticks
  restart_time: 168 #hours
  dragon_timer: "6, 7, 3 - 20:00"
  teleport_location:
  prev_commands:
    - ''
  after_commands:
    - ''
  dragon_commands:
    - "test"
language:
  teleport: "&e&lEND &7We've moved you to the spawn."
  restarting: "&e&lEND &7Cleaning the world..."
  restart_complete: "&e&lEND &7Clean complete."
  time_string: "&7%d &edays, &7%d &ehours, &7%d &eminutes, &7%d &eseconds"

