name: EndCore
version: '${project.version}'
main: rama.EndCore
api-version: 1.19
authors: [ ImRama ]
description: End world utilities plugin. Made for UnBloque
softdepend:
  - PlaceHolderAPI
commands:
  endcore: